[package]
name = "bitsh"
version = "0.1.0"
authors = ["Martin <martin@bitbleep.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
bitvec = { version = "0.21", default-features = false, features = [] }
proptest = "1"